apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/danielkaeser2023/greeting-app/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: greeting-config

images:
- name: greeting-service
  newName: ghcr.io/danielkaeser2023/greeting-service
  newTag: a25fdddb5be746ad9bbc530ccf6a1f69b0926387

replicas:
- count: 2
  name: greeting-service
